<template>
  <span
    ref="triggerRef"
    @mouseenter="show = true"
    @mouseleave="show = false"
    class="bg-gray-200 text-gray-800 dark:bg-gray-600 dark:text-slate-50 px-2 py-0.5 rounded text-sm truncate min-w-0"
  >
    <slot /> <!-- Elemen target -->
  </span>

  <teleport to="body">
    <div
      v-if="show && content"
      :style="style"
      class="fixed z-50 bg-gray-700 text-white text-sm px-3 py-2 rounded shadow-lg whitespace-pre-line max-w-xs mt-16"
    >
      <div v-html="parsedContent"></div>
      <div class="pt-2 font-medium">Generated by AI</div>
    </div>
  </teleport>
</template>

<script setup lang="ts">
import { ref, computed, watchEffect } from 'vue'
// import { escapeHtml } from './utils'

// Props
const props = defineProps<{ content: string }>()

// Refs
const show = ref(false)
const triggerRef = ref<HTMLElement | null>(null)
const style = ref<Record<string, string>>({})

function escapeHtml(text: string): string {
  return text.replace(/[&<>"']/g, (match) => {
    switch (match) {
      case '&': return '&amp;'
      case '<': return '&lt;'
      case '>': return '&gt;'
      case '"': return '&quot;'
      case "'": return '&#039;'
      default: return match
    }
  })
}


// Parse content: escape HTML, convert **bold**, and \n to <br>
const parsedContent = computed(() => {
  const raw = props.content || ''
  const escaped = escapeHtml(raw)
  return escaped
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\n/g, '<br>')
})

// Posisi tooltip
watchEffect(() => {
  if (show.value && triggerRef.value) {
    const rect = triggerRef.value.getBoundingClientRect()
    style.value = {
      top: `${rect.top + rect.height / 2}px`,
      left: `${rect.right + 8}px`,
      transform: 'translateY(-50%)',
      position: 'fixed',
    }
  }
})
</script>

<style scoped>
strong {
  font-weight: 500; /* medium */
}
</style>