// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250624062132_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("backend.Models.SchemaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FixedPartSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPrimaryKey")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasStructuredPrivilegeCheck")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsColumnTable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInsertOnly")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLogged")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReplica")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeriesTable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemTable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTenantSharedData")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTenantSharedMetadata")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUserDefinedType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TableOid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TableType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemporaryTableType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Schemas");
                });
#pragma warning restore 612, 618
        }
    }
}
