<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount } from 'vue'
import DbDiagram from '../components/DbDiagram.vue'
import ArrowRight from '../components/icons/ArrowRight.vue'
import Relation from '../components/icons/Relation.vue'
import AceEditor from '../components/AceEditor.vue'
import FooterCustom from '../components/Footer.vue'
import { useAppStore } from '../stores/app'
const app = useAppStore()

app.setTitle('SQL Command')
const query = ref('SELECT * FROM XYZ')
const leftWidth = ref(200)
let isResizing = false

const startResize = () => {
  isResizing = true
  document.body.style.cursor = 'w-resize'
}

const handleMouseMove = (e: MouseEvent) => {
  if (isResizing) {
    leftWidth.value = Math.max(e.clientX, 200) // minimum width
  }
}

const stopResize = () => {
  isResizing = false
  document.body.style.cursor = ''
}

onMounted(() => {
  window.addEventListener('mousemove', handleMouseMove)
  window.addEventListener('mouseup', stopResize)
})

onBeforeUnmount(() => {
  window.removeEventListener('mousemove', handleMouseMove)
  window.removeEventListener('mouseup', stopResize)
})

// const handleKeydown = (event: KeyboardEvent) => {
//   const textarea = event.target as HTMLTextAreaElement

//   if (event.key === 'Tab') {
//     event.preventDefault()

//     const start = textarea.selectionStart
//     const end = textarea.selectionEnd

//     // Sisipkan tab
//     const before = query.value.substring(0, start)
//     const after = query.value.substring(end)

//     query.value = before + '\t' + after

//     // Kembalikan kursor setelah tab
//     nextTick(() => {
//       textarea.selectionStart = textarea.selectionEnd = start + 1
//     })
//   }
// }
</script>

<template>
  <div>
    <div class="flex">
      <div class="p-2" :style="{ maxWidth: leftWidth + 'px' }">
        <div class="relative w-full max-w-sm">
          <span class="absolute inset-y-0 left-0 flex items-center pl-2 text-gray-500">
            🔍
          </span>
          <input type="text" placeholder="Search..."
            class="w-full pl-8 pr-4 py-1 border rounded focus:border-blue-300" />
        </div>
        <div class="mt-2">
          <div class="flex items-center overflow-hidden gap-1">
            <button onclick="toggle(this)" class="shrink-0">➕</button>
            <span class="font-bold shrink-0">MARA</span>
            <span data-tooltip-target="tooltip-right" data-tooltip-placement="right"
              class="bg-gray-300 px-2 py-0.5 rounded text-sm truncate min-w-0">
              General Material Table Table Table Table Table Table Tables
            </span>

            <div id="tooltip-right" role="tooltip"
              class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white bg-gray-900 rounded-lg shadow-xs opacity-0 tooltip dark:bg-gray-700">
              Berisi data umum master material, seperti nomor material, <br>
              deskripsi dasar, dan jenis material. Ini adalah fondasi <br>
              untuk pengelolaan stok dan produk. <br>
              <div class="pt-2 font-medium">Generated by AI</div>
              <div class="tooltip-arrow" data-popper-arrow></div>
            </div>
          </div>
          <ul class="ml-4 mb-3">
            <li>
              <button onclick="toggle(this)" class="mr-1">➕</button>
              <span>DocType</span>
            </li>
            <li>
              <button onclick="toggle(this)" class="mr-1">➕</button>
              <span>DocType</span>
            </li>
          </ul>

        </div>
      </div>

      <div id="resizer" class="cursor-w-resize w-[5px] bg-gray-300" @mousedown="startResize"></div>

      <div class="p-2 w-full ps-3">
        <div>
          <AceEditor v-model="query" />
          <!-- <textarea class="min-w-[700px] min-h-[150px] outline-none px-2 py-1 bg-slate-200 rounded-md resize"
            v-model="query" @keydown="handleKeydown" placeholder="Enter your query..."></textarea> -->
          <div class="flex items-center space-x-3 mt-2">
            <button
              class="flex items-center text-white bg-blue-700 hover:bg-blue-800 focus:ring-blue-300 font-medium rounded-sm text-sm px-3 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800 leading-none focus:ring-0 focus:border-0">
              <span class="me-2 inline-flex items-center">
                <ArrowRight size="12px" />
                <!-- <Spinner size="14px" /> -->
              </span>
              <span class="leading-none">Execute</span>
            </button>

            <span class="text-sm leading-none">Limit Rows:</span>
            <input type="number"
              class="w-14 outline-none px-2 py-[6px] bg-slate-200 rounded-md text-center text-sm leading-none"
              value="50" />
          </div>

        </div>

        <div class="mt-10">
          <div>
            <div class="relative">
              <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                  <tr>
                    <th scope="col" class="px-6 py-3 border border-gray-300">
                      Product name
                    </th>
                    <th scope="col" class="px-6 py-3 border border-gray-300">
                      Color
                    </th>
                    <th scope="col" class="px-6 py-3 flex gap-1 border border-gray-300">
                      Category
                      <button data-modal-target="default-modal" data-modal-toggle="default-modal">
                        <!-- <img src="https://api.iconify.design/line-md:lightbulb.svg" class="w-[17px]"> -->
                        <Relation />
                      </button>
                    </th>
                    <th scope="col" class="px-6 py-3 border border-gray-300">
                      Price
                    </th>
                  </tr>
                </thead>
                <tbody>
                  <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 border-gray-200">
                    <td scope="row"
                      class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white border border-gray-300">
                      Apple MacBook Pro 17"
                    </td>
                    <td class="px-6 py-4 border border-gray-300">
                      Silver
                    </td>
                    <td class="px-6 py-4 border border-gray-300">
                      Laptop
                    </td>
                    <td class="px-6 py-4 border border-gray-300">
                      $2999
                    </td>
                  </tr>
                  <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 border-gray-200">
                    <td scope="row"
                      class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white border border-gray-300">
                      Microsoft Surface Pro
                    </td>
                    <td class="px-6 py-4 border border-gray-300">
                      White
                    </td>
                    <td class="px-6 py-4 border border-gray-300">
                      Laptop PC
                    </td>
                    <td class="px-6 py-4 border border-gray-300">
                      $1999
                    </td>
                  </tr>
                  <tr class="bg-white dark:bg-gray-800">
                    <td scope="row"
                      class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white border border-gray-300">
                      Magic Mouse 2
                    </td>
                    <td class="px-6 py-4 border border-gray-300">
                      Black
                    </td>
                    <td class="px-6 py-4 border border-gray-300">
                      Accessories
                    </td>
                    <td class="px-6 py-4 border border-gray-300">
                      $99
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>

            <!-- <DbDiagram /> -->

          </div>
        </div>

        <FooterCustom />

      </div>
    </div>

    <!-- Main modal -->
    <div id="default-modal" tabindex="-1" aria-hidden="true"
      class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 justify-center items-center w-full md:inset-0 h-[calc(100%-1rem)] max-h-full">
      <div class="relative w-full max-w-4xl max-h-full">
        <!-- Modal content -->
        <div class="relative bg-white rounded-lg shadow-sm dark:bg-gray-700">
          <!-- Modal header -->
          <div
            class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600 border-gray-200">
            <h3 class="text-xl font-semibold text-gray-900 dark:text-white">
              Diagram
            </h3>
            <button type="button"
              class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white"
              data-modal-hide="default-modal">
              <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                viewBox="0 0 14 14">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
              </svg>
              <span class="sr-only">Close modal</span>
            </button>
          </div>
          <!-- Modal body -->
          <div class="p-4 md:p-5 space-y-4">
            <DbDiagram />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
